### ISSUE TITLE
Is it "expect" or "except"?

### ISSUE THREAD

**Issue by nmandyam** [NativeScript/nativescript-sdk-examples-js#124]
In both the places where the doc talks of the fromObjectRecursive method, it says: "This function will create new Observable for each nested object (expect arrays and functions) from supplied JavaScript object." Ummm, is that actually "This function will create new Observable for each nested object (except arrays and functions) from supplied JavaScript object."? That's a whole different thing. If it DOES actually "expect" to see arrays and functions in the supplied object, could you please make that clearer?

**Comment by NickIliev** [comment]
It should be **except** - good catch! WIll post a PR to fix the documentation,

**Comment by NickIliev** [comment]
Resolved via https://github.com/NativeScript/nativescript-sdk-examples-js/pull/131
