### ISSUE TITLE
Feature Request: Allow reordering of examples in component article

### ISSUE THREAD

**Issue by MartoYankov** [NativeScript/nativescript-sdk-examples-js#52]
The current behavior is that all examples are ordered alphabetically based on their folder names. This is fine for the moment where 'Basics' and 'Code-Behind' are very high alphabetically, but if I want to add an example starting with 'Android-...' or 'Angular-...' it's not fine.

As a proposal, this can be done in the metadata.md file below the '---' line like so: 'example-order: basics, code-behind, android-example...'. If there is an example that is not mentioned in this list or there is no list, they should be ordered alphabetically.

**Comment by tsonevn** [comment]
PR : https://github.com/NativeScript/nativescript-sdk-examples-js/pull/62
