### ISSUE TITLE
This is not JS examples, this is typescript

### ISSUE THREAD

**Issue by JuanAntelo** [NativeScript/nativescript-sdk-examples-js#77]
Hi,

I navigated to this page thinking it would show me examples in vanilla Javascript. However, the example uses typescript

**Comment by tsonevn** [comment]
Hi @JuanAntelo, 
In the sample project, we have provided samples in TypeScript as well as vanilla JavaScript. For example:
If we take the [application-settings/basics](https://github.com/NativeScript/nativescript-sdk-examples-js/tree/master/app/ns-framework-modules-category/application-settings/basics)   folder. There is a  `basics-page.js` file, which contains the JavaScript example and file which includes `-ts-` in its name (`basics-ts-page.ts`), which contains the TypeScript example. Keep in mind that the `basics-ts-page.js` is the transpiled file, and if you need a JavaScript example, you should open the js file, which do not includes `-ts-` in its name.
