### ISSUE TITLE
new FlexboxLayout

### ISSUE THREAD

**Issue by b02505048** [NativeScript/nativescript-sdk-examples-js#88]
I have read the [docs](https://docs.nativescript.org/ui/ns-ui-widgets/layouts)
But I can't find out how to import the `FlexboxLayout` from module 

I tried 
```
const FlexboxLayout = require("tns-core-modules/ui/layouts/flexbox-layout").FlexboxLayout;
```
and it crashed when I called `let fbl = new FlexboxLayout()`
Any idea?

**Comment by tsonevn** [comment]
Hi @b02505048,
Excuse me for the delayed reply.
For JavaScript project, you can import the FlexboxLayout the same way you have shown above.
```
const FlexboxLayout = require("tns-core-modules/ui/layouts/flexbox-layout").FlexboxLayout;
```
For TypeScript
```
import {FlexboxLayout} from "tns-core-modules/ui/layouts/flexbox-layout";
```
